### ISSUE TITLE
stream_.lastTickTimestamp not initialized

### ISSUE THREAD

**Issue by sonoro1234** [thestk/rtaudio#83]
Hi,

Calling in sequence:

dac:openStream(...
dac:setStreamTime(10) <- set to whatever different from 0
dac:getStreamTime() -> gives 10
dac:startStream()
dac:getStreamTime() -> gives whatever

this is because stream_.lastTickTimestamp is still not initialized when second getStreamTime is called
the first getStreamTime is OK because
````
 if ( stream_.state != STREAM_RUNNING || stream_.streamTime == 0.0 )
    return stream_.streamTime;
````

not sure about how could this be fixed

Best Regards
victor bombi

**Comment by garyscavone** [comment]
I think I fixed this with commit #62f62cf90364040706863bd574d340e7c82216c3.

**Comment by sonoro1234** [comment]
If getStreamTime is called after startStream but when tickStreamTime is still not called by the callback lastTickTimestamp is too old. I think that startStream should update lastTickTimestamp also.

**Comment by sonoro1234** [comment]
Just tried above idea with asio and works as expected.
To do a PR, the easiest way would be to modify RtAudio::startStream by adding
```
#if defined( HAVE_GETTIMEOFDAY )
  gettimeofday( &stream_.lastTickTimestamp, NULL );
#endif
```
but stream_ is not a member of RtAudio.

Instead of modifing each RtApi specialization of startStream perhaps all could be reworked: create RtApi:startStreamPre which would call gettimeofday and after RtApiSpecialization:startStream
and then call it from RtAudio:

```
RtApi::startStreamPre(void) {
    #if defined( HAVE_GETTIMEOFDAY )
      gettimeofday( &stream_.lastTickTimestamp, NULL );
    #endif
    rtapi_->startStream();
}
inline void RtAudio :: startStream( void ) { return rtapi_->startStreamPre(); }
```
@garyscavone what do you think about that?
